### ISSUE TITLE
how to create custom razor view template?

### ISSUE THREAD

**Issue by neozhu** [TrackableEntities/AspNetCore.ApiControllers.Templates#4]
Is there a simple solution or sample code?

**Comment by tonysneed** [comment]
@neozhu Yes, this repository contains a [sample solution](https://github.com/TrackableEntities/AspNetCore.ApiControllers.Templates/blob/master/sample/TemplatesSample.sln).  So just clone the repo and you'll have a sample at your fingertips.

The [ReadMe](https://github.com/TrackableEntities/AspNetCore.ApiControllers.Templates/blob/master/README.md) contains step-by-step instructions for replicating the sample.
